// AUTO-GENERATED by scripts/build-content.mjs from src/content/** (Keystatic CMS).
// Do not edit by hand — edit content in the /keystatic admin, then rebuild.
/* eslint-disable */
export const projectsData = [
  {
    "slug": "rajasthani-sammelan",
    "name": "Rajasthani Sammelan",
    "vertical": "Education",
    "location": "Mumbai",
    "statHighlight": "497 cameras · 15 institutes · 94% uptime",
    "summary": "497 cameras across 15 institutes — still running strong more than a decade after installation.",
    "featured": true,
    "services": [
      "cctv",
      "access-control"
    ],
    "challenge": "Fifteen separate educational institutes needed unified surveillance that administrators could trust for the long haul — not a system that quietly degrades after the first year.",
    "solution": "Konect designed and installed 497 cameras across all 15 institutes in 2014, then backed the deployment with an Annual Maintenance Contract and preventive maintenance schedule to keep every camera recording.",
    "result": "More than ten years on, the system is still in service with 94% uptime verified through AMC records — the clearest proof that Konect builds installations that last.",
    "facts": [
      {
        "label": "Cameras",
        "value": "497"
      },
      {
        "label": "Institutes",
        "value": "15"
      },
      {
        "label": "Installed",
        "value": "2014"
      },
      {
        "label": "Verified uptime",
        "value": "94%"
      }
    ],
    "gallery": [],
    "year": 2014,
    "heroImage": "/images/projects/rajasthani-sammelan.webp"
  },
  {
    "slug": "raheja-imperia",
    "name": "Raheja Imperia",
    "vertical": "Residential",
    "location": "Lower Parel, Mumbai",
    "statHighlight": "406 cameras · 58 floors · 2 wings",
    "summary": "406 cameras covering 58 floors across two wings of a premium South Mumbai tower.",
    "featured": true,
    "services": [
      "cctv",
      "video-door-phone"
    ],
    "challenge": "A premium 58-floor, two-wing residential tower in Lower Parel needed comprehensive, discreet coverage worthy of one of South Mumbai's most prestigious addresses.",
    "solution": "Konect engineered four cameras per floor across both wings — 406 cameras in total — with cabling and equipment planned around the building's vertical structure.",
    "result": "Every floor, lobby and common area is covered by a single coherent system, delivering the always-on security residents of a premium address expect.",
    "facts": [
      {
        "label": "Cameras",
        "value": "406"
      },
      {
        "label": "Floors",
        "value": "58"
      },
      {
        "label": "Wings",
        "value": "2"
      },
      {
        "label": "Per floor",
        "value": "4 cameras"
      }
    ],
    "gallery": [],
    "heroImage": "/images/projects/raheja-imperia.webp"
  },
  {
    "slug": "navjiwan-society",
    "name": "Navjiwan Chembur Sindhi Society",
    "vertical": "Residential",
    "location": "Chembur, Mumbai",
    "statHighlight": "110 cameras · 8 NVRs · 32 societies",
    "summary": "One centrally controlled system spanning a 32-society complex, with intelligent loop planning that saved significant wiring.",
    "featured": true,
    "services": [
      "cctv",
      "intercom"
    ],
    "challenge": "A 32-society complex needed to be monitored as one — but connecting that many buildings naively would have meant a costly, sprawling tangle of cable.",
    "solution": "Konect deployed 110 cameras on 8 NVRs under central control, using intelligent loop planning and underground wiring for inter-society connectivity to cut cable runs dramatically.",
    "result": "The entire 32-society complex is managed from one control point, with a clean underground backbone that saved significant wiring cost and disruption.",
    "facts": [
      {
        "label": "Cameras",
        "value": "110"
      },
      {
        "label": "NVRs",
        "value": "8"
      },
      {
        "label": "Societies",
        "value": "32"
      },
      {
        "label": "Control",
        "value": "Centralised"
      }
    ],
    "gallery": [],
    "heroImage": "/images/projects/navjiwan-society.webp"
  },
  {
    "slug": "umrao-hospitals",
    "name": "Umrao Hospitals",
    "vertical": "Healthcare",
    "location": "Mira Road, Mumbai",
    "statHighlight": "120 cameras · entrusted by Voltas",
    "summary": "A 120-camera hospital deployment offloaded to Konect by Voltas — a major trust signal.",
    "featured": false,
    "services": [
      "cctv"
    ],
    "challenge": "A busy Mira Road hospital required reliable, round-the-clock surveillance across patient, public and restricted areas.",
    "solution": "The project was offloaded to Konect by Voltas, and Konect installed 120 cameras across the facility in 2011.",
    "result": "Voltas entrusting the work to Konect is a trust signal in itself — and the hospital gained complete, dependable coverage.",
    "facts": [
      {
        "label": "Cameras",
        "value": "120"
      },
      {
        "label": "Installed",
        "value": "2011"
      },
      {
        "label": "Entrusted by",
        "value": "Voltas"
      },
      {
        "label": "Sector",
        "value": "Healthcare"
      }
    ],
    "gallery": [],
    "year": 2011,
    "heroImage": "/images/projects/umrao-hospitals.webp"
  },
  {
    "slug": "splendor-complex",
    "name": "Splendor Complex",
    "vertical": "Residential",
    "location": "JVLR, Mumbai",
    "statHighlight": "250+ cameras under AMC · growing",
    "summary": "An AMC of 250+ cameras that keeps growing — 28 elevator cameras and 40 new cameras added and counting.",
    "featured": false,
    "services": [
      "cctv"
    ],
    "challenge": "A large JVLR complex needed both ongoing maintenance of an extensive camera estate and a partner who could expand coverage as needs grew.",
    "solution": "Konect maintains an AMC of 250+ cameras, recently adding 28 elevator cameras and a further 40 new cameras to the system.",
    "result": "A growing account where the client keeps adding cameras — the surest sign that the maintenance relationship is working.",
    "facts": [
      {
        "label": "Cameras under AMC",
        "value": "250+"
      },
      {
        "label": "Elevator cameras",
        "value": "28"
      },
      {
        "label": "Recently added",
        "value": "40"
      },
      {
        "label": "Status",
        "value": "Growing"
      }
    ],
    "gallery": [],
    "heroImage": "/images/projects/splendor-complex.webp"
  },
  {
    "slug": "shubhada-polymers",
    "name": "Shubhada Polymers",
    "vertical": "Manufacturing",
    "location": "Lonavala",
    "statHighlight": "4 plants · 32 cameras each · 128 total",
    "summary": "Full planning, wiring and execution across four plants — 32 cameras per plant, 128 in total.",
    "featured": false,
    "services": [
      "cctv"
    ],
    "challenge": "Four manufacturing plants needed consistent, standardised surveillance with the planning and wiring handled end-to-end.",
    "solution": "Konect handled full planning, wiring and execution, deploying 32 cameras at each of the four plants for 128 cameras total.",
    "result": "A uniform surveillance standard across all four Lonavala plants, executed entirely in-house by Konect.",
    "facts": [
      {
        "label": "Plants",
        "value": "4"
      },
      {
        "label": "Cameras / plant",
        "value": "32"
      },
      {
        "label": "Total cameras",
        "value": "128"
      },
      {
        "label": "Scope",
        "value": "Plan · wire · execute"
      }
    ],
    "gallery": [],
    "heroImage": "/images/projects/shubhada-polymers.webp"
  },
  {
    "slug": "styrotech-industries",
    "name": "Styrotech Industries",
    "vertical": "Manufacturing",
    "location": "Ranjangaon (MIDC)",
    "statHighlight": "64 IP cameras · remote-viewable from Mumbai",
    "summary": "64 IP cameras in a MIDC industrial zone, all viewable from the Mumbai office — a remote-monitoring showcase.",
    "featured": false,
    "services": [
      "cctv",
      "wireless"
    ],
    "challenge": "An industrial plant in the Ranjangaon MIDC zone needed surveillance that head office in Mumbai could watch live, while keeping wiring and maintenance costs down.",
    "solution": "Konect installed 64 IP cameras designed to be viewed remotely, with the full feed accessible from the Mumbai office and the layout planned to save wiring and maintenance.",
    "result": "Management in Mumbai monitors the entire Ranjangaon plant in real time — a working showcase of Konect's remote-monitoring capability.",
    "facts": [
      {
        "label": "IP cameras",
        "value": "64"
      },
      {
        "label": "Zone",
        "value": "Ranjangaon MIDC"
      },
      {
        "label": "Monitoring",
        "value": "Remote from Mumbai"
      },
      {
        "label": "Designed for",
        "value": "Lower wiring cost"
      }
    ],
    "gallery": [],
    "heroImage": "/images/projects/styrotech-industries.webp"
  },
  {
    "slug": "marathon-icon",
    "name": "Marathon Icon",
    "vertical": "Residential",
    "location": "Lower Parel, Mumbai",
    "statHighlight": "149 cameras",
    "summary": "A 149-camera deployment for a Lower Parel residential tower.",
    "featured": false,
    "services": [
      "cctv"
    ],
    "challenge": "A Lower Parel residential tower needed thorough coverage of its common areas and entry points.",
    "solution": "Konect installed 149 cameras across the building.",
    "result": "Comprehensive, single-system coverage for residents in one of Mumbai's busiest precincts.",
    "facts": [
      {
        "label": "Cameras",
        "value": "149"
      },
      {
        "label": "Location",
        "value": "Lower Parel"
      },
      {
        "label": "Sector",
        "value": "Residential"
      }
    ],
    "gallery": [],
    "heroImage": "/images/projects/marathon-icon.webp"
  },
  {
    "slug": "mandev-tubes",
    "name": "Mandev Tubes",
    "vertical": "Manufacturing",
    "location": "Umbergaon",
    "statHighlight": "126 cameras across 2 plants",
    "summary": "Two plants secured — 78 cameras at Plant 1 and 48 at Plant 2, 126 in total.",
    "featured": false,
    "services": [
      "cctv"
    ],
    "challenge": "Two separate plants in Umbergaon needed surveillance scaled to each site's size.",
    "solution": "Konect installed 78 cameras at Plant 1 and 48 at Plant 2 — 126 cameras across the two facilities.",
    "result": "Both plants are covered to a consistent standard, sized appropriately to each site.",
    "facts": [
      {
        "label": "Plant 1",
        "value": "78 cameras"
      },
      {
        "label": "Plant 2",
        "value": "48 cameras"
      },
      {
        "label": "Total",
        "value": "126"
      },
      {
        "label": "Location",
        "value": "Umbergaon"
      }
    ],
    "gallery": [],
    "heroImage": "/images/projects/mandev-tubes.webp"
  },
  {
    "slug": "roshan-spaces",
    "name": "Roshan Spaces",
    "vertical": "Commercial",
    "location": "Bandra, Mumbai",
    "statHighlight": "Asia's largest hoarding",
    "summary": "A marquee Bandra commercial project — home to Asia's largest hoarding.",
    "featured": false,
    "services": [
      "cctv"
    ],
    "challenge": "A landmark Bandra commercial site — host to Asia's largest hoarding — called for surveillance befitting a high-profile location.",
    "solution": "Konect delivered surveillance for this marquee commercial address.",
    "result": "A flagship commercial reference in Konect's Mumbai portfolio.",
    "facts": [
      {
        "label": "Location",
        "value": "Bandra"
      },
      {
        "label": "Notability",
        "value": "Asia's largest hoarding"
      },
      {
        "label": "Sector",
        "value": "Commercial"
      }
    ],
    "gallery": [],
    "heroImage": "/images/projects/roshan-spaces.webp"
  },
  {
    "slug": "kgs-grounds",
    "name": "KGS Grounds",
    "vertical": "Sports & Recreation",
    "location": "Jogeshwari East, Mumbai",
    "statHighlight": "Fully wireless · access point on every pole",
    "summary": "A fully wireless camera network with a wireless access point on every pole — no trenching, full coverage.",
    "featured": false,
    "services": [
      "wireless",
      "cctv"
    ],
    "challenge": "An open recreational ground in Jogeshwari East couldn't be wired conventionally without major civil work.",
    "solution": "Konect built a fully wireless camera network with a wireless access point on every pole, covering the grounds without trenching cable.",
    "result": "Complete coverage of an open ground using wireless infrastructure — a template for sites where wiring isn't practical.",
    "facts": [
      {
        "label": "Network",
        "value": "Fully wireless"
      },
      {
        "label": "Per pole",
        "value": "Wireless access point"
      },
      {
        "label": "Location",
        "value": "Jogeshwari East"
      },
      {
        "label": "Sector",
        "value": "Sports & Recreation"
      }
    ],
    "gallery": [],
    "heroImage": "/images/projects/kgs-grounds.webp"
  }
];
export const servicesData = [
  {
    "slug": "cctv",
    "name": "CCTV Implementation & Support",
    "short": "End-to-end IP camera systems — design, installation, wiring, NVR setup and remote monitoring.",
    "icon": "Cctv",
    "image": "/images/existing/services/showcase/cctv.webp",
    "keywords": [
      "CCTV installation Mumbai",
      "security camera installation Mumbai",
      "IP camera installation services"
    ]
  },
  {
    "slug": "access-control",
    "name": "Biometrics & Access Control",
    "short": "Fingerprint, face recognition and card-based access for corporate and residential entry points.",
    "icon": "Fingerprint",
    "image": "/images/existing/services/showcase/access-control.webp",
    "keywords": [
      "biometric access control Mumbai",
      "access control system Mumbai"
    ]
  },
  {
    "slug": "time-attendance",
    "name": "Time Attendance Systems",
    "short": "Biometric employee attendance tracking that plugs straight into your access control.",
    "icon": "CalendarClock",
    "image": "/images/existing/services/showcase/time-attendance.webp",
    "keywords": [
      "time attendance system Mumbai",
      "biometric attendance"
    ]
  },
  {
    "slug": "video-door-phone",
    "name": "Video Door Phones",
    "short": "See and speak to visitors before you open the door — residential and commercial.",
    "icon": "Video",
    "image": "/images/existing/services/showcase/video-door-phone.webp",
    "keywords": [
      "video door phone installation",
      "video door phone Mumbai"
    ]
  },
  {
    "slug": "intercom",
    "name": "Intercom Systems",
    "short": "Multi-building, multi-floor communication networks for societies and campuses.",
    "icon": "Network",
    "image": "/images/existing/services/showcase/intercom.webp",
    "keywords": [
      "intercom system installation Mumbai",
      "society intercom"
    ]
  },
  {
    "slug": "pa-system",
    "name": "Public Address Systems",
    "short": "Campus-wide, hospital and industrial PA installations that are heard everywhere.",
    "icon": "Megaphone",
    "image": "/images/existing/services/showcase/pa-system.webp",
    "keywords": [
      "PA system installation",
      "public address system Mumbai"
    ]
  },
  {
    "slug": "home-automation",
    "name": "Home Automation",
    "short": "Smart device integration, lighting control and automated security for modern homes.",
    "icon": "House",
    "image": "/images/existing/services/showcase/home-automation.webp",
    "keywords": [
      "home automation Mumbai",
      "smart home Mumbai"
    ]
  },
  {
    "slug": "wireless",
    "name": "Wireless Camera Systems",
    "short": "Pole-mounted wireless networks for grounds and estates where wiring isn't practical.",
    "icon": "RadioTower",
    "image": "/images/existing/services/showcase/wireless.webp",
    "keywords": [
      "wireless camera system",
      "wireless CCTV Mumbai"
    ]
  }
];
export const clientsData = [
  {
    "name": "Amazon",
    "src": "/images/existing/clients/amazon.png"
  },
  {
    "name": "Reliance",
    "src": "/images/existing/clients/reliance.png"
  },
  {
    "name": "Tata Power",
    "src": "/images/existing/clients/tata-power.jpg"
  },
  {
    "name": "Samsung",
    "src": "/images/existing/clients/samsung.png"
  },
  {
    "name": "3M",
    "src": "/images/existing/clients/3m.png"
  },
  {
    "name": "Sony",
    "src": "/images/existing/clients/sony.png"
  },
  {
    "name": "Honda",
    "src": "/images/existing/clients/honda.png"
  },
  {
    "name": "Mahindra Logistics",
    "src": "/images/existing/clients/mahindra-logistics.png"
  },
  {
    "name": "Idea",
    "src": "/images/existing/clients/idea.png"
  },
  {
    "name": "Subway",
    "src": "/images/existing/clients/subway.png"
  },
  {
    "name": "Cloudtail",
    "src": "/images/existing/clients/cloudtail.png"
  },
  {
    "name": "Kokilaben Hospital",
    "src": "/images/existing/clients/kokilaben.png"
  },
  {
    "name": "Hakkasan",
    "src": "/images/existing/clients/hakkasan.png"
  },
  {
    "name": "Manchester United Café",
    "src": "/images/existing/clients/manchester-united-cafe.png"
  },
  {
    "name": "Graviss Hospitality",
    "src": "/images/existing/clients/graviss.png"
  },
  {
    "name": "Rustomjee",
    "src": "/images/existing/clients/rustomjee.png"
  },
  {
    "name": "Angel Broking",
    "src": "/images/existing/clients/angel-broking.png"
  },
  {
    "name": "Aquafina",
    "src": "/images/existing/clients/aquafina.png"
  },
  {
    "name": "Lava",
    "src": "/images/existing/clients/lava.png"
  },
  {
    "name": "Wellness Forever",
    "src": "/images/existing/clients/wellness-forever.png"
  },
  {
    "name": "Mayfair",
    "src": "/images/existing/clients/mayfair.png"
  },
  {
    "name": "Omkar",
    "src": "/images/existing/clients/omkar.png"
  },
  {
    "name": "Lakhani's",
    "src": "/images/existing/clients/lakhani.png"
  },
  {
    "name": "48 Fitness",
    "src": "/images/existing/clients/48-fitness.png"
  },
  {
    "name": "All India Balkanji Bari",
    "src": "/images/existing/clients/all-india-balkanji-bari.png"
  },
  {
    "name": "Auto Cooling",
    "src": "/images/existing/clients/auto-cooling.png"
  },
  {
    "name": "Bhavans College",
    "src": "/images/existing/clients/bhavans-college.png"
  },
  {
    "name": "Cachet Pharma",
    "src": "/images/existing/clients/cachet-pharma.png"
  },
  {
    "name": "Café Mangii",
    "src": "/images/existing/clients/cafe-mangii.png"
  },
  {
    "name": "Citrus Check Inns",
    "src": "/images/existing/clients/citrus-check-inns.png"
  },
  {
    "name": "Citrus Hotels",
    "src": "/images/existing/clients/citrus-hotels.png"
  },
  {
    "name": "Clover",
    "src": "/images/existing/clients/clover.png"
  },
  {
    "name": "Dental Care Clinic",
    "src": "/images/existing/clients/dental-care-clinic.png"
  },
  {
    "name": "D&J Appliances",
    "src": "/images/existing/clients/dj-appliances.png"
  },
  {
    "name": "Durgadevi Saraf College",
    "src": "/images/existing/clients/durgadevi-saraf.png"
  },
  {
    "name": "East West Travels",
    "src": "/images/existing/clients/east-west-travels.png"
  },
  {
    "name": "Epic Studios",
    "src": "/images/existing/clients/epic-studios.png"
  },
  {
    "name": "Falafel's",
    "src": "/images/existing/clients/falafel.png"
  },
  {
    "name": "Ferro Equip",
    "src": "/images/existing/clients/ferro-equip.png"
  },
  {
    "name": "Foresight Opticals",
    "src": "/images/existing/clients/foresight-opticals.png"
  },
  {
    "name": "Fundsupermart",
    "src": "/images/existing/clients/fundsupermart.png"
  },
  {
    "name": "GCO Technology",
    "src": "/images/existing/clients/gco-technology.png"
  },
  {
    "name": "Genelife Clinical Research",
    "src": "/images/existing/clients/genelife.png"
  },
  {
    "name": "GM Fabrics",
    "src": "/images/existing/clients/gm-fabrics.png"
  },
  {
    "name": "Good Day Food",
    "src": "/images/existing/clients/good-day-food.png"
  },
  {
    "name": "GS Worldwide",
    "src": "/images/existing/clients/gs-worldwide.png"
  },
  {
    "name": "Gurukrupa Plastics",
    "src": "/images/existing/clients/gurukrupa-plastics.png"
  },
  {
    "name": "Gyan Kendra",
    "src": "/images/existing/clients/gyan-kendra.png"
  },
  {
    "name": "Hrishikesh Fabrics",
    "src": "/images/existing/clients/hrishikesh-fabrics.png"
  },
  {
    "name": "IIT Powai",
    "src": "/images/existing/clients/iit-powai.png"
  },
  {
    "name": "ISKCON Food Relief Foundation",
    "src": "/images/existing/clients/iskcon-food-relief.png"
  },
  {
    "name": "i-XL Technologies",
    "src": "/images/existing/clients/ixl-technologies.png"
  },
  {
    "name": "Joey's Pizza",
    "src": "/images/existing/clients/joeys-pizza.png"
  },
  {
    "name": "K A Hospitality",
    "src": "/images/existing/clients/ka-hospitality.png"
  },
  {
    "name": "Kalptaru Films",
    "src": "/images/existing/clients/kalptaru-films.png"
  },
  {
    "name": "KEM Hospital",
    "src": "/images/existing/clients/kem-hospital.png"
  },
  {
    "name": "K.G. Seksaria English School",
    "src": "/images/existing/clients/kges.png"
  },
  {
    "name": "K.G. Seksaria Sanskar School",
    "src": "/images/existing/clients/kgss.png"
  },
  {
    "name": "Khandani Rajdhani",
    "src": "/images/existing/clients/khandani-rajdhani.png"
  },
  {
    "name": "Krish Infosystems",
    "src": "/images/existing/clients/krish-infosystems.png"
  },
  {
    "name": "KVIT",
    "src": "/images/existing/clients/kvit.png"
  },
  {
    "name": "Lilac Insights",
    "src": "/images/existing/clients/lilac-insights.png"
  },
  {
    "name": "L.R. Maheshwari School",
    "src": "/images/existing/clients/lrm-school.png"
  },
  {
    "name": "Markss Infotech",
    "src": "/images/existing/clients/markss-infotech.png"
  },
  {
    "name": "Meraki Salon & Spa",
    "src": "/images/existing/clients/meraki.png"
  },
  {
    "name": "Mirah Hospitality",
    "src": "/images/existing/clients/mirah-hospitality.png"
  },
  {
    "name": "Mukta Enterprises",
    "src": "/images/existing/clients/mukta.png"
  },
  {
    "name": "Nexus Life Care",
    "src": "/images/existing/clients/nexus-lifecare.png"
  },
  {
    "name": "NL College",
    "src": "/images/existing/clients/nl-college.png"
  },
  {
    "name": "Optic Zone",
    "src": "/images/existing/clients/optic-zone.png"
  },
  {
    "name": "Palette Food Court",
    "src": "/images/existing/clients/palette.png"
  },
  {
    "name": "Patel Roadways",
    "src": "/images/existing/clients/patel-roadways.png"
  },
  {
    "name": "Poonam Couriers",
    "src": "/images/existing/clients/poonam-couriers.png"
  },
  {
    "name": "Hotel Rang Sharda",
    "src": "/images/existing/clients/rang-sharda.png"
  },
  {
    "name": "RSIP",
    "src": "/images/existing/clients/rsip.png"
  },
  {
    "name": "Sarex",
    "src": "/images/existing/clients/sarex.png"
  },
  {
    "name": "Sharada Gyan Peeth",
    "src": "/images/existing/clients/sharada-gyan-peeth.png"
  },
  {
    "name": "Shreya Events",
    "src": "/images/existing/clients/shreya-events.png"
  },
  {
    "name": "Sidhanth Cine Vision",
    "src": "/images/existing/clients/sidhanth-cine-vision.png"
  },
  {
    "name": "SNDT Women's University",
    "src": "/images/existing/clients/sndt.png"
  },
  {
    "name": "Spice Lane",
    "src": "/images/existing/clients/spice-lane.png"
  },
  {
    "name": "SSK Retails",
    "src": "/images/existing/clients/ssk-retails.png"
  },
  {
    "name": "Sterling",
    "src": "/images/existing/clients/sterling.png"
  },
  {
    "name": "Sunny Hotel",
    "src": "/images/existing/clients/sunny-hotel.png"
  },
  {
    "name": "The Health Store",
    "src": "/images/existing/clients/the-health-store.png"
  },
  {
    "name": "Umrao Hospitals",
    "src": "/images/existing/clients/umrao-hospitals.png"
  },
  {
    "name": "The United",
    "src": "/images/existing/clients/united.png"
  },
  {
    "name": "Universal Communications",
    "src": "/images/existing/clients/universal-communications.png"
  },
  {
    "name": "West Coast Fine Foods",
    "src": "/images/existing/clients/west-coast-foods.png"
  },
  {
    "name": "Yogi Executive Hotel",
    "src": "/images/existing/clients/yogi-executive.png"
  },
  {
    "name": "Yogi Hotel",
    "src": "/images/existing/clients/yogi-hotel.png"
  },
  {
    "name": "Yogurt",
    "src": "/images/existing/clients/yogurt.png"
  }
];
export const testimonialsData = [
  {
    "quote": "Our cameras used to go dead for weeks and we'd only find out when we actually needed footage. Since Konect took over the AMC, the quarterly visits catch problems before we even notice them.",
    "role": "Secretary",
    "area": "Residential society · Malad West"
  },
  {
    "quote": "What sold our committee was the service history — we can finally see exactly what was checked and when. And the helpdesk actually picks up.",
    "role": "Chairman",
    "area": "Co-op housing society · Chembur"
  },
  {
    "quote": "We switched after years of chasing our old vendor for every fault. Konect's response time and standby equipment have made a real difference for our residents.",
    "role": "Treasurer",
    "area": "Housing society · Powai"
  }
];
export const siteData = {
  "name": "Konect",
  "tagline": "Securing Mumbai Since 2010",
  "url": "https://www.konect.in",
  "description": "Mumbai's trusted security & surveillance partner since 2010. CCTV, access control, intercom and AMC services for residential societies, commercial complexes and industrial facilities.",
  "phoneDisplay": "+91 98202 11679",
  "phoneTel": "+919820211679",
  "whatsappDisplay": "+91 98202 11679",
  "whatsappNumber": "919820211679",
  "email": "info@konect.in",
  "hours": "Mon–Sat · 9:30 AM – 6:30 PM",
  "web3formsKey": "2a0f65c2-242e-448e-9145-f50d2bdfb6e5",
  "addressStreet": "Orlem, Malad West",
  "addressLocality": "Mumbai",
  "addressRegion": "Maharashtra",
  "addressPostalCode": "400064",
  "mapsLink": "https://www.google.com/maps/place/Konect+-+Training+and+Technical+Services",
  "mapsEmbed": "https://maps.google.com/maps?q=Konect+-+Training+and+Technical+Services,+Orlem,+Malad+West,+Mumbai&output=embed",
  "facebook": "https://www.facebook.com/Konectinfonet/"
};
export const statsData = [
  {
    "value": 400,
    "suffix": "+",
    "label": "Customers Served"
  },
  {
    "value": 300,
    "suffix": "+",
    "label": "Societies Secured"
  },
  {
    "value": 200,
    "suffix": "+",
    "label": "Active AMCs"
  },
  {
    "value": 16,
    "suffix": "+",
    "label": "Years in Business"
  }
];
export const homeHeroData = {
  "badge": "CCTV AMC specialists for Mumbai housing societies",
  "headlinePrefix": "We keep CCTV running across",
  "headlineAccent": "300+ Mumbai societies",
  "subhead": "Konect runs 200+ active AMC contracts across Mumbai — quarterly preventive maintenance, a real helpdesk and fast response that keep your society's cameras recording when it matters.",
  "strip": [
    {
      "image": "/images/projects/strip/0/image.webp",
      "alt": "CCTV cameras securing a Mumbai street"
    },
    {
      "image": "/images/projects/strip/1/image.webp",
      "alt": "A Konect technician installing a CCTV camera on a Mumbai building"
    },
    {
      "image": "/images/projects/strip/2/image.webp",
      "alt": "A modern IP surveillance camera installed by Konect"
    }
  ]
};
export const verticalsData = [
  {
    "slug": "education",
    "name": "Education",
    "icon": "GraduationCap",
    "stat": "497 cameras across 15 institutes"
  },
  {
    "slug": "healthcare",
    "name": "Healthcare",
    "icon": "HeartPulse",
    "stat": "120-camera hospital deployment"
  },
  {
    "slug": "manufacturing",
    "name": "Manufacturing",
    "icon": "Factory",
    "stat": "Multi-plant industrial surveillance"
  },
  {
    "slug": "residential",
    "name": "Residential",
    "icon": "Building2",
    "stat": "300+ societies secured"
  },
  {
    "slug": "commercial",
    "name": "Commercial",
    "icon": "Store",
    "stat": "Marquee Mumbai landmarks"
  },
  {
    "slug": "sports-recreation",
    "name": "Sports & Recreation",
    "icon": "Trophy",
    "stat": "Fully wireless ground coverage"
  }
];
