// Generates src/lib/content-data.ts from the Keystatic content files in
// src/content/**. Runs automatically before `dev` and `build` (see package.json),
// so editing content in /keystatic + rebuilding updates the whole site.
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const C = (...p) => path.join(ROOT, "src/content", ...p);

function readDir(dir) {
  const full = C(dir);
  if (!fs.existsSync(full)) return [];
  return fs
    .readdirSync(full)
    .filter((f) => f.endsWith(".json"))
    .map((f) => ({
      slug: f.replace(/\.json$/, ""),
      data: JSON.parse(fs.readFileSync(path.join(full, f), "utf8")),
    }));
}
function readJson(rel) {
  const full = C(rel);
  return fs.existsSync(full)
    ? JSON.parse(fs.readFileSync(full, "utf8"))
    : null;
}
const byOrder = (a, b) => (a.data.order ?? 999) - (b.data.order ?? 999);

const projectsData = readDir("projects")
  .sort(byOrder)
  .map(({ slug, data }) => {
    const o = {
      slug,
      name: data.name,
      vertical: data.vertical,
      location: data.location,
      statHighlight: data.statHighlight,
      summary: data.summary,
      featured: !!data.featured,
      services: data.services ?? [],
      challenge: data.challenge,
      solution: data.solution,
      result: data.result,
      facts: data.facts ?? [],
      gallery: (data.gallery ?? []).filter(Boolean),
    };
    if (data.year != null) o.year = data.year;
    if (data.heroImage) o.heroImage = data.heroImage;
    return o;
  });

const servicesData = readDir("services")
  .sort(byOrder)
  .map(({ slug, data }) => ({
    slug,
    name: data.name,
    short: data.short,
    icon: data.icon,
    image: data.image ?? null,
    keywords: data.keywords ?? [],
  }));

const clientsData = readDir("clients")
  .sort(byOrder)
  .map(({ data }) => ({ name: data.name, src: data.logo }));

const testimonialsData = readDir("testimonials")
  .sort(byOrder)
  .map(({ data }) => ({ quote: data.quote, role: data.role, area: data.area }));

const siteData = readJson("settings/site.json");
const statsData = readJson("settings/stats.json")?.items ?? [];
const homeHeroData = readJson("settings/home-hero.json");
const verticalsData = readJson("settings/verticals.json")?.items ?? [];

const j = (v) => JSON.stringify(v, null, 2);
const out = `// AUTO-GENERATED by scripts/build-content.mjs from src/content/** (Keystatic CMS).
// Do not edit by hand — edit content in the /keystatic admin, then rebuild.
/* eslint-disable */
export const projectsData = ${j(projectsData)};
export const servicesData = ${j(servicesData)};
export const clientsData = ${j(clientsData)};
export const testimonialsData = ${j(testimonialsData)};
export const siteData = ${j(siteData)};
export const statsData = ${j(statsData)};
export const homeHeroData = ${j(homeHeroData)};
export const verticalsData = ${j(verticalsData)};
`;

fs.writeFileSync(path.join(ROOT, "src/lib/content-data.ts"), out);
console.log("content-data.ts generated:", {
  projects: projectsData.length,
  services: servicesData.length,
  clients: clientsData.length,
  testimonials: testimonialsData.length,
  stats: statsData.length,
  verticals: verticalsData.length,
});
